# Generated by Django 5.2 on 2025-04-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blackboard",
            fields=[
                (
                    "code",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=20)),
                ("image_height", models.IntegerField()),
                ("image_width", models.IntegerField()),
                (
                    "black_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Image_Blackboard",
                        to="action.blackboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=500)),
                ("font_size", models.PositiveIntegerField()),
                (
                    "font_color",
                    models.CharField(
                        choices=[("red", "Red"), ("black", "Black"), ("blue", "Blue")],
                        default="black",
                        max_length=20,
                    ),
                ),
                (
                    "black_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Text_Blackboard",
                        to="action.blackboard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blackboard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="action.user"
            ),
        ),
    ]
